#!/bin/bash
# Wrapper script to easily run the different docker operations

CMD=$1
DISTRO=$2
IMAGE=clangtest/$DISTRO
DISTRO_CACHE=/tmp/distro-cache
WORKING_DIR=`pwd`

run(){
  # run the docker image
  docker run $IMAGE
}

build(){
  # build the docker image from the distro folder
  if [ -d $DISTRO/tmp ] ; then
    rm -r $DISTRO/tmp
  fi
  mkdir -p $DISTRO/tmp
  cp ../llvm.sh $DISTRO/tmp
  cp build.sh get_proj.sh $DISTRO/tmp
  docker build -t $IMAGE $DISTRO
}

login(){
  # run the image and login with bash
  # useful for debugging the image
  docker run -it -u root $IMAGE bash
}

buildrun(){
  # build and run the image
  build
  run
}

buildlogin(){
  # build and run bash in the image
  build
  login
}

if [ ! -d "$DISTRO" ] ; then
  echo "Could not find $DISTRO folder!"
  exit 1
fi

$1
