#!/bin/sh
if test ! -d /tmp/buildd/*/reports/; then
	echo "No code coverage report found; skipping"
	exit 0;
else
	cmd='cd /tmp/buildd/*/reports/'
	echo $cmd
	eval $cmd
	cmd='tar czvf ../codecoverage.tar.gz coverage/'
	echo $cmd
	eval $cmd
	cmd='cp ../codecoverage.tar.gz /tmp/buildd/'
	echo $cmd
	eval $cmd
	cmd='ls -alh $(pwd)/../codecoverage.tar.gz /tmp/buildd/codecoverage.tar.gz'
	echo $cmd
	eval $cmd

fi
