#!/bin/sh
if test ! -d /tmp/buildd/llvm-*/cov-int/; then
	echo "No coverity report found; skipping"
	exit 0;
else
	cmd='cd /tmp/buildd/llvm-*/'
	echo $cmd
	eval $cmd
	cmd='ls -al cov-int/; tar czvf /tmp/buildd/llvm.tgz cov-int/'
	echo $cmd
	eval $cmd


	minimumsize=190000
	actualsize=$(du -k /tmp/buildd/llvm.tgz | cut -f 1)
	if [ $actualsize -ge $minimumsize ]; then
		apt-get install --yes --no-install-recommends --force-yes curl ca-certificates
		curl --form project=llvm --form token=IcZw6jNXoeVFDe34wf1WPQ \
		    --form email=sylvestre@debian.org \
		    --form file=@/tmp/buildd/llvm.tgz \
		    --form version=$(date "+%Y-%m-%d_%H-%M-%S") \
		    --form description="llvm-toolchain" \
		    https://scan.coverity.com/builds?project=llvm
        else
		cat cov-int/build-log.txt
                echo "Unexpected filesize. Should be at least $minimumsize (found $actualize)"
                exit 1
        fi
fi
