#!/bin/sh

# To update the binary, ssh on the image machine
# scp the file into /opt/

if test ! -d /tmp/buildd/source/cov-int/; then
	echo "No coverity report found; skipping"
	echo "ls -al /tmp/buildd/source/ :"
	ls -al /tmp/buildd/source/
	exit 0;
else
	cmd='cd /tmp/buildd/source/'
	echo $cmd
	eval $cmd
	cmd='ls -al cov-int/; tar czvf /tmp/buildd/llvm.tgz cov-int/'
	echo $cmd
	eval $cmd


	minimumsize=190000
	actualsize=$(du -k /tmp/buildd/llvm.tgz | cut -f 1)
	cd /tmp/buildd
	if [ $actualsize -ge $minimumsize ]; then
		apt-get install --yes --no-install-recommends curl ca-certificates jq
		curl -X POST \
			 -d version="Version" \
			 -d description="Description" \
			 -d email=sylvestre@mozilla.com \
			 -d token=IcZw6jNXoeVFDe34wf1WPQ \
			 -d file_name="llvm.tgz" \
			 https://scan.coverity.com/projects/869/builds/init \
			| tee response
		upload_url=$(jq -r '.url' response)
		build_id=$(jq -r '.build_id' response)
		curl -X PUT \
			 --header 'Content-Type: application/json' \
			 --upload-file llvm.tgz \
			 $upload_url
		curl -X PUT \
			 -d token=IcZw6jNXoeVFDe34wf1WPQ \
			 https://scan.coverity.com/projects/232/builds/$build_id/enqueue
	else
		cat cov-int/build-log.txt
		echo "Unexpected filesize. Should be at least $minimumsize (found $actualize)"
		exit 1
	fi
fi
