#!/bin/sh
dir=`ls -1d /tmp/scan-build-*|tail -1`
if test -z $dir; then
	echo "No scan-build report found; skipping"
	exit 0;
else
	cmd='cd /tmp/'
	echo $cmd
	eval $cmd
        cmd='ls -al /tmp/scan-build*/*'
        echo $cmd
        eval $cmd
	cmd="mv $dir scan-build"
	echo $cmd
	eval $cmd
	cmd='tar czvf /tmp/buildd/scan-build.tar.gz scan-build/'
	echo $cmd
	eval $cmd
fi
