#!/bin/sh

set -ex

if echo "$DEB_BUILD_OPTIONS" | grep "scan-build"; then
    apt-get install --yes --no-install-recommends --force-yes wget gnupg apt-transport-https ca-certificates
    echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main" >> /etc/apt/sources.list
    wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
    apt-get update
    apt-get install --yes --no-install-recommends --force-yes clang-tools-13
    # remove old artifacts
    rm -rf /tmp/scan-build-*
fi
