#!/bin/sh

set -ex

if echo "$DEB_BUILD_OPTIONS" | grep "scan-build"; then
    echo "deb http://apt.llvm.org/unstable/ llvm-toolchain main" >> /etc/apt/sources.list
    apt-get update
    apt-get install --yes --no-install-recommends --force-yes clang-4.0
fi
