#!/bin/sh

set -ex
apt-get install --assume-yes --no-install-recommends lsb-release wget
DIST=$(lsb_release -sc)
ID=$(lsb_release -is| awk '{print tolower($0)}')
# Detect the LLVM version

PKG_DIR=$(readlink -f /build/*/debian/..)
LLVM_VERSION=$(cd $PKG_DIR && dpkg-parsechangelog | sed -rne "s,^Version: 1:([0-9]+).*,\1,p")

echo "DIST = $DIST"
echo "ID = $ID"
echo "LLVM_VERSION = $LLVM_VERSION"

if test "$DIST" = "bionic" -a $LLVM_VERSION -ge 14; then
    # Install gcc 11 to get C++ 20 features
    # Only needed from llvm 14
    apt install -y software-properties-common gpg
    add-apt-repository -y ppa:ubuntu-toolchain-r/test
    apt-get update
    apt-get install g++-11 --assume-yes --no-install-recommends
fi

if test "$DIST" = "stretch"; then
    apt-get install --assume-yes --no-install-recommends apt-transport-https
    echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/stretch-backport.list
    # for libarchive13 (needed for cmake)
    echo "deb http://ftp.debian.org/debian stretch-backports-sloppy main" >> /etc/apt/sources.list.d/stretch-backport.list

    # for a more recent version of gcc
    apt install -y software-properties-common apt-transport-https
    add-apt-repository -y  "deb https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu xenial main"

    apt-get update
    apt-get install libarchive13 --assume-yes -t stretch-backports-sloppy
    apt-get install debhelper cmake --assume-yes -t stretch-backports
    apt-get install g++-7 --assume-yes
    apt -y --purge remove aptitude

    apt install -y zlib1g-dev liblzma-dev libbz2-dev libzstd-dev binutils bzip2 libperl5.24 make patch perl perl-modules-5.24 rename xz-utils libseccomp2
    PKG="lsb-base_10.2019051400_all.deb libdpkg-perl_1.19.7_all.deb apt_1.8.2.3_amd64.deb libapt-pkg5.0_1.8.2.3_amd64.deb dpkg_1.19.7_amd64.deb libdpkg-dev_1.19.7_amd64.deb dpkg-dev_1.19.7_all.deb apt-utils_1.8.2.3_amd64.deb libapt-inst2.0_1.8.2.3_amd64.deb"
    for f in $PKG; do
        wget --no-check-certificate https://sylvestre.ledru.info/bordel/$f
    done
    dpkg -i $PKG
    rm *.deb

fi # end stretch
