#!/bin/sh

set -ex
apt-get install --assume-yes --no-install-recommends lsb-release wget time
DIST=$(lsb_release -sc)
ID=$(lsb_release -is| awk '{print tolower($0)}')
# Detect the LLVM version

PKG_DIR=$(readlink -f /build/*/debian/..)
LLVM_VERSION=$(cd $PKG_DIR && dpkg-parsechangelog | sed -rne "s,^Version: 1:([0-9]+).*,\1,p")

echo "DIST = $DIST"
echo "ID = $ID"
echo "LLVM_VERSION = $LLVM_VERSION"

if test "$DIST" = "bionic" -a $LLVM_VERSION -ge 14; then
    # install some packages before to avoid some confusions between bionic & bionic-updates
    apt install libgrpc++-dev protobuf-compiler-grpc libprotobuf-dev protobuf-compiler --assume-yes --no-install-recommends
    if test "$(arch)" = "s390x" -o "$(arch)" = "aarch64" ; then
        echo "deb http://ports.ubuntu.com/ubuntu-ports bionic-updates main" >> /etc/apt/sources.list.d/bionic.list
    else
        echo "deb http://www-ftp.lip6.fr/pub/linux/distributions/Ubuntu/ bionic-updates main"  >> /etc/apt/sources.list.d/bionic.list
    fi
    apt update
    apt-get install g++-7 --assume-yes --no-install-recommends
fi
