#!/bin/sh

set -ex

apt-get install --yes --no-install-recommends --force-yes ccache
# ccache stats
ccache -s

echo "Also start sccache to test"
cd /tmp/
wget --no-check-certificate https://github.com/opencollab/llvm-jenkins.debian.net/raw/master/sccache
chmod +x sccache
export SCCACHE_GCS_BUCKET=apt-llvm-org-sccache
export SCCACHE_GCS_RW_MODE=READ_WRITE
export SCCACHE_GCS_KEY_PATH=~/secret-gcp-storage.json
export SCCACHE_VERBOSE_STATS=1
./sccache --show-stats||true
