#!/bin/sh
set -ex
cd /tmp/
apt-get install --yes --no-install-recommends --force-yes curl
DIST=$(lsb_release -sc)
ID=$(lsb_release -is| awk '{print tolower($0)}')
if test "$DIST" = "stretch" -o "$DIST" = "xenial" -o "$DIST" = "bionic"; then
	ARCH=$(uname -m)
	if test "$ARCH" = "i686"; then
		ARCH="i386"
	fi
	curl -o cmake.tar.gz  --insecure https://sylvestre.ledru.info/bordel/cmake-3.18.1-Linux-$ARCH.tar.gz
	tar zxvf cmake.tar.gz
	mv cmake-* cmake
fi
